### ISSUE TITLE
First word must just touch middle square

### ISSUE THREAD

**Issue by flibustenet** [shiblon/entrogo#1]
In french (at least), the first word can start anywhere if it touch the square of the middle, i think you start it only on 7,7 but it could start on 3,4 and benefit of letter x 2

**Comment by shiblon** [comment]
That's true: there is no strategy in this code. The only time you would care about which tile is on the middle square is if you were employing a form of lookahead, e.g., "if I put the second tile on the middle square, then that makes it less likely that pluralizing this word will open up a high-scoring move."

Since this code is only intended to look at the current scoring possibilities, it doesn't have any way of determining that one tile placement is better than another on the first move.

We could, of course, try to add more heuristics to it, a few of which might look like this:

- A singular word should not end before a column (or row) that contains a multi-word score square, because 's' is common and that makes adversarial moves more likely.

- If you aren't using all of your letters on this move, but it looks like there is a high probability of getting letters that complete a high-scoring word (based on statistics on which tiles are left, intersection with current word, etc.), then you might want to position the word differently.

- If you have a model of the vocabulary of your opponent, you can adjust probabilities that way, too.

All of these things are fun and interesting, and part of what makes the game itself more interesting than just a glorified dictionary search, but I think they might be out of scope for this particular code. I think of this code as just that: a glorified dictionary search. Thus, the first move can be anywhere, and might as well be at 7,7. :-)
